### PR TITLE
Call contained trait types' `class_init` and set `this_class` in `class_init`

### PR DESCRIPTION
**Pull request by SylvainCorlay**
... rather than in `instance_init`.

### CODE REVIEW

**Comment by minrk** [comment]
Can you show an example of the difference in behavior this causes (in a test, for example)?

**Comment by SylvainCorlay** [comment]
The gist of it is that

- if `trait.this_type` is set in `instance_init`, it is done every time the `HasTraits` class is instantiated, which is redundant.
- if `trait.this_type` is set in `class_init`, it is done every time the `MetaHasTraits` class is instantiated, which is only on declaration of new trait types.

**Comment by SylvainCorlay** [comment]
Oh ok, I did not expect this would go in 4.1

**Comment by minrk** [comment]
Good point. Probably shoudn't have merged it, but I think it'll be okay.

**Comment by minrk** [comment]
We can revert and re-merge after the actual release if you'd be more comfortable.

**Comment by SylvainCorlay** [comment]
I am fine with the new state - was just expressing surprise...

**Comment by rmorshea** [comment]
At the moment, because `setup_class` iterates over `cls.__dict__`, it wouldn't be possible to add attributes to the class inside `class_init` because `cls.__dict__` will change size and thus an error will be thrown. This forces users to explicitly define new attributes in `setup_class` rather than dynamically in `class_init`, is this a desireable behavior?

**Comment by rmorshea** [comment]
...the alternative being to iterate over `cls.__dict__.copy()`

**Comment by SylvainCorlay** [comment]
@rmorshea good point. 

It seems that it is not an issue at the moment since class_init does not add things to the class. I don't think that `class_init` should edit the class though but better safe than sorry.

I would be ok to copy the dict first in `setup_class`.

**Comment by rmorshea** [comment]
Should I make a pr for that then?

**Comment by rmorshea** [comment]
Also, is there any reason that `this_class` can't be set inside `class_init` on the descriptor, or at the very least inside `setup_class`? It would mean that not all descriptors would have this attribute when `class_init` is called, however since it seems like the philosophy so far has been that descriptors should be agnostic to the presence of other descriptors, that shouldn't be too much of an issue.

**Comment by SylvainCorlay** [comment]
Regarding the setting of `this_class` and `name`, I thought of putting it inside `class_init` but did not do it in this PR.

**Comment by rmorshea** [comment]
In #129 I decided not to set `this_class` and `name` in `class_init` just to keep `BaseDescriptor` as simple as possible and instead put it in `setup_class`.

**Pull request merged**
