### PR TITLE
add trait setters/getters

### PR DESCRIPTION
**Pull request by rmorshea**
example:

```python
from traitlets import HasTraits, Int

class Test(HasTraits):
    
    n = Int()
    
    def _n_setter(self, value):
        return int(value)
        
    def _n_getter(self, value):
        return float(value)

t = Test()
t.n = 1.2

print(t.n)
```

print result: `1.0`

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
You could also use custom validators to achieve the same thing.

```Python
from traitlets import HasTraits, Float
import math

class Test(HasTraits):

    n = Float()

    def _n_validate(self, value, trait):
        return math.floor(value)

t = Test()
t.n = 1.2

print(t.n)
```

**Comment by SylvainCorlay** [comment]
Actually, custom validators might be what you where looking for since the beginning. You can coerce/validate value using other attributes' values before trait notifications fire. Hence it is rather flexible.

**Comment by rmorshea** [comment]
That example was more a way to get the idea across, so I guess a more exhaustive demo for the setter would be.

```python
from traitlets import HasTraits, Float

class Test(HasTraits):

    n = Float()

    def _n_setter(self, value):
        return float(value)

t = Test()
t.n = '1.2'

print(t.n)
```

**Comment by rmorshea** [comment]
the main issue with cross validation is that it occurs after the main validation does

**Comment by SylvainCorlay** [comment]
You can also create a CFloat trait type that cast passed values to Float... For example I often use a CInstance trai type that casts to the specified type...

**Comment by rmorshea** [comment]
So this gets into some of the nuance I think. The use case I posted on the #60 involved an attribute `_transformSet` whose value needed to be updated regardless of whether the `_transform` had changed. This would be fine except for the fact that using `with self.hold_trait_notifications():` would prevent that call from being fired if I were to use `_name_validate` as a way to trigger that update.

**Comment by SylvainCorlay** [comment]
`self.hold_trait_notifications()` will run the cross validation when the context manager is released.

**Comment by SylvainCorlay** [comment]
Since I don't know the specifics of the matplotlib use case, can you post a more complete toy example of what you want to achieve. I still think that it is likely that you can already do everything you need with custom trait types and/or custom validation.

**Comment by rmorshea** [comment]
I forgot about that. I think the setters may be covered by `_name_validate`. The only differences being that the setter here would basically allow for trivial conversions without inheritance and that I (maybe presumptuously) included an `on_trait_set` function. The only way that I can see to cover the getter though would be to have linked change notifiers that span both instances and attributes. As cool as that would be, I think it would be a bit hairy to actually implement.

**Comment by rmorshea** [comment]
maybe that's not as bad as I'm thinking it would be though...

**Comment by SylvainCorlay** [comment]
Should we close this one?

**Comment by rmorshea** [comment]
I think so.

**Comment by rmorshea** [comment]
the getters might resurface though if underscore access is a feature in matplotlib rather than a bug

**Pull request closed without merging**
