### PR TITLE
DOC: changes for 4.1

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
:+1: Currently at the airport but am fine with merging.
I noticed that there is still a reference to `_**_changed` in the main "using traitlets" document.

**Comment by minrk** [comment]
Thanks, fixed the example to use the new API.

**Comment by SylvainCorlay** [comment]
Merged from a 32791 feet altitude, at 489 MPH somewhere above Nebraska.

**Comment by minrk** [comment]
4.1.0b1 is up

**Comment by ellisonbg** [comment]
Nice!!!

**Comment by SylvainCorlay** [comment]
Awesome. @ellisonbg, @minrk do you want to post something on the mailing list so that people try it?

**Comment by minrk** [comment]
@SylvainCorlay that's a good idea. Would you like to do it? I think you and @jasongrout know the highlights of the new APIs better than I do.

**Comment by SylvainCorlay** [comment]
Ok, I am preparing something.

**Comment by SylvainCorlay** [comment]
What do you think of this: https://gist.github.com/SylvainCorlay/01e8cc1f214678532e95

**Comment by minrk** [comment]
:+1:

**Pull request merged**
