### PR TITLE
get documentation building

### PR DESCRIPTION
**Pull request by justinkao**
- ran sphinx-quickstart and customized documentation build files
- copied over css and template from IPython
- changed title/summary of document to match new project name

### CODE REVIEW

**Comment by minrk** [comment]
Please *do not* copy css and template from IPython. It should start from scratch with sphinx defaults. It should also not include the IPython logo.

**Comment by minrk** [comment]
conf.py should also be started from sphinx defaults instead of copying IPython's. IPython's conf.py was excluded from this repo on purpose.

**Comment by minrk** [comment]
@justinkao are you planning to address comments on this, or should we finish it up?

**Comment by justinkao** [comment]
Intending to, but I haven't had time to look at this again since Pycon. Feel free to take it over if it's urgent?

**Comment by minrk** [comment]
finished up in #8

**Pull request closed without merging**
