### PR TITLE
Fix KeyError in Application.get_default_logging_config

### LINKED ISSUE #723: KeyError in get_default_logging_config
If sys.executable is set to pythonw.exe calling get_default_logging_config results in a KeyError because it tries to delete a key that doesn't exist.

https://github.com/ipython/traitlets/blob/main/traitlets/config/application.py#L259

```
2022-05-12 15:42:05,811 - ERROR :   File "C:\Users\tony\miniconda3\envs\py39-7165\lib\site-packages\traitlets\config\application.py", line 259, in get_default_logging_config
2022-05-12 15:42:05,812 - ERROR :     del config["handlers"]["loggers"]
2022-05-12 15:42:05,812 - ERROR : KeyError: 'loggers'

### PR DESCRIPTION
**Pull request by tonyroberts**
Fixes #723

### CODE REVIEW

**Comment by bollwyvl** [comment]
Thanks for giving it a shot! 

Perhaps before trying to fix it, we should get a more representative test case for #724. 

When actually fixing, we might also be able to do some less "invasive" things like `config.pop('...', None)`? Note that some of the failures issues are from a recent `pip` change

**Comment by tonyroberts** [comment]
Hi @bollwyvl,

No worries, happy to help if I can.

If you look at the code you'll see the "config" dict is declared just above and with the keys "handlers" and "loggers", but not "handlers"/"loggers" as a nested dict ((https://github.com/ipython/traitlets/blob/f43e658703a9dfee5ae33e4cac2070a62534f4e6/traitlets/config/application.py#L226)). This looks like a typo or oversight that maybe should have been caught when the original (recent) change (https://github.com/ipython/traitlets/commit/b5b5085353391b7dd9b9da2f4f6f730c84afd9c6) was reviewed. I agree using pop would be more conservative, but the dict is only declared just above so maybe not necessary IMHO.

Of course happy to accept any other fix you propose, and if you can add a test for this error then so much the better. Anyway, I hope this has helped make it clear what the problem is even if you decide it's not the appropriate fix.

Thanks!
Tony

**Comment by tonyroberts** [comment]
@oliver-sanders may have a view as the author of the original commit

**Comment by oliver-sanders** [comment]
@tonyroberts, thanks for looking in, this fix looks fine to me.

We have Windows tests in CI but they didn't pick up the issue because they weren't using pythonw. 

Short of running tests with pythonw here's the best approach to testing I could come up with: https://github.com/ipython/traitlets/commit/56138647108a0ec1034a1ed3e78fdeb62476cdcf

**Comment by tonyroberts** [comment]
Great! Thanks @oliver-sanders. I'll merge your commit into this PR :)

**Comment by oliver-sanders** [comment]
@tonyroberts If you close/re-open this PR the tests should pass.

**Comment by tonyroberts** [comment]
Closing and re-opening doesn't seem to have re-run the tests. I'm away this week but will try force pushing on Monday and see if that does it.

**Comment by JanB1** [comment]
Hey @tonyroberts, were you able to get back on this?

**Comment by tonyroberts** [comment]
@JanB1 Sorry, I totally forgot! I've rebased and pushed and looks like the tests are running now...

**Comment by tonyroberts** [comment]
@JanB1 The same test is failing in the same way on the main branch, I don't think the failure is related to this PR. If you fix it on the main branch I can rebase this one to be sure.

**Comment by JanB1** [comment]
@tonyroberts Well, I'm not a contributor to the main branch. Sadly can't help you there. I only came over from the jupyter/qtconsole#543 issue.

**Comment by JanB1** [comment]
@blink1073 @tonyroberts I see Steven ran the same tests and seems like he was able to fix the error that was causing the test to fail. Maybe now it should run through?

**Comment by blink1073** [comment]
Kicking CI

**Comment by JanB1** [comment]
@blink1073 🎉

**Pull request merged**
