### PR TITLE
Adding transform attribute to directional link

### PR DESCRIPTION
**Pull request by SylvainCorlay**
@ellisonbg

### CODE REVIEW

**Comment by ellisonbg** [comment]
+1

**Comment by minrk** [comment]
@SylvainCorlay @ellisonbg  do you want this in 4.1? I think we can cut the beta today.

**Comment by SylvainCorlay** [comment]
I would rather not postpone the release so it can certainly go without it!
Are you making a 4.1 or a 5.0 beta?

**Comment by minrk** [comment]
...now I don't remember what we decided, and when I look over the conversation again it seems inconclusive. 4.1?

**Comment by SylvainCorlay** [comment]
I don't think that we decided anything.

**Comment by ellisonbg** [comment]
I prefer to get this into 4.1

**Comment by SylvainCorlay** [comment]
Added a test.

**Comment by minrk** [comment]
AOK

**Pull request merged**
