### PR TITLE
run tests with py.test

### PR DESCRIPTION
**Pull request by minrk**
instead of nose2.

And use codecov instead of coveralls while we're at it, since that's what we do now.

### CODE REVIEW

**Comment by minrk** [comment]
nose2 was recently introduced as a solution to nose being mostly abandoned, but pytest seems a bit more common, and what we use on most of our projects that have moved away from nose. Not a lot of changes to make.

**Comment by Carreau** [comment]
+1

**Comment by rmorshea** [comment]
Should change the docs for running the tests.

**Comment by minrk** [comment]
@rmorshea good catch, done.

**Comment by Carreau** [comment]
Thanks @minrk  !

**Pull request merged**
