### PR TITLE
WIP: calculation decorator for linking multiple inputs throught a calculation to a single output

### PR DESCRIPTION
**Pull request by maartenbreddels**
Sometimes you want to link the values of multiple traits to another one, using observe can be cumbersome, so I was using this decorator for it. The screenshot I think explains a lot. Not polished code, would like some feedback first. It seems quite similar to the transform in dlink, but that is one input to one output, this is multiple inputs to a single output (although I can imaging having multiple outputs as well).

screen shot 2017-07-24 at 21 40 49

### CODE REVIEW

**Comment by minrk** [comment]
This is cool! (cc @SylvainCorlay for review)

**Comment by jasongrout** [comment]
This is cool. I'm not sure this is the appropriate level to have a default attribute ('value'). That is pretty specific to ipywidgets, but I don't see many other HasTraits classes out there attach special meaning to a 'value' trait.

**Comment by maartenbreddels** [comment]
The default is definitely up for discussion, but from a user point of view it's pretty user friendly. Whatever we decide on how choosing the default trait, we can do the same for `(js)(d)link`.
For widgets we can think about doing a `jscalcalation` variant, which can take a code snippet or (optionally) rely on [flexx transpiling](https://flexx.readthedocs.io/en/latest/pyscript/index.html), which would restore balance between `link/jslink` and `calculation/jscalculation`.

**Comment by Carreau** [comment]
Closing as state for 3 years Labelling accordingly to easily reopen if necessary. Will try to do some cleanup to not have multiple pages of stale PR.

**Pull request closed without merging**
