### PR TITLE
Remove depedency towards ipython_genutils.

### PR DESCRIPTION
**Pull request by lucasg**
Hi,

**ipython_genutils** is marked for deprecation, you might as well incorporate only the functionalities needed and remove the import.  Traitlets is much better as a stand-alone library anyway.
The 9 commits incrementally add external utilities from ipython_genutils into the traitlets package (every commits pass the nosetest tests on my machine). 
Note : I've copied py3compat in its entirety, but only a portion is useful. You might need to trim it down, or abstracting away using six.

Cheers,

lucasg

### Results from Travis 

https://travis-ci.org/lucasg/traitlets/builds/113952990

### Results from tests (on my machine)
```
`(ipython_env) [lucasg traitlets]$ python --version
Python 3.5.1

(ipython_env) [lucas traitlets]$ pip freeze
coverage==4.0.3
coveralls==1.1
decorator==4.0.9
docopt==0.6.2
ipython==5.0.0.dev0
ipython-genutils==0.2.0.dev0
nose==1.3.7
path.py==8.1.2
pexpect==4.0.1
pickleshare==0.6
prompt-toolkit==0.59
ptyprocess==0.5.1
Pygments==2.1.3
requests==2.9.1
simplegeneric==0.8.1
six==1.10.0
traitlets==4.2.0.dev0
wcwidth==0.1.6
wheel==0.29.0

(ipython_env) [lucas traitlets]$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': 'eb2f497',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': REDACTED,
 'ipython_version': '5.0.0.dev',
 'os_name': 'posix',
 'platform': 'Linux-4.1.18-2-MANJARO-x86_64-with-glibc2.3.4',
 'sys_executable': REDACTED,
 'sys_platform': 'linux',
 'sys_version': '3.5.1 (default, Dec  7 2015, 12:58:09) \n[GCC 5.2.0]'}




(ipython_env) [lucasg traitlets]$ nosetests --exe --with-coverage --cover-package traitlets traitlets
...................................................................................................................................................................................S................S............................................................................................
Name                               Stmts   Miss  Cover   Missing
----------------------------------------------------------------
traitlets.py                           3      0   100%   
traitlets/_version.py                  2      0   100%   
traitlets/config.py                    3      0   100%   
traitlets/config/application.py      326    131    60%   54, 77-82, 103, 205, 209, 229-233, 277-278, 282-304, 308-317, 320-331, 335-350, 357-378, 391-393, 401-406, 410, 415-425, 480, 484-487, 499-500, 503-504, 523, 536-542, 564, 579-581, 589-591, 620-627, 635-638
traitlets/config/configurable.py     213     17    92%   51, 54, 59, 77, 329-330, 337, 404, 408, 434-435, 465-471, 513
traitlets/config/loader.py           438     55    87%   54-55, 138-147, 180, 248, 289, 297, 356-357, 432, 435, 531-532, 538, 541-544, 603, 714, 751, 753-757, 827, 830, 837, 861, 863, 868, 878-879, 881, 897, 922-933
traitlets/log.py                      10      1    90%   21
traitlets/traitlets.py              1130    157    86%   50, 110-112, 144, 186, 188, 202-203, 214, 217, 219, 312, 402, 407, 423-424, 445-447, 452-456, 510-512, 540-542, 555, 582, 595, 653, 677, 908, 924-925, 991-992, 1039, 1067, 1134-1135, 1144, 1147-1148, 1241-1247, 1274, 1377-1378, 1392-1396, 1422, 1431, 1476, 1501, 1574, 1576, 1591, 1715-1718, 1748, 1764-1767, 1773-1816, 1849-1852, 1872-1875, 1896-1899, 1912-1916, 1924-1927, 1942-1949, 1984-1987, 1996, 2002, 2006-2009, 2015-2016, 2019-2027, 2081, 2089, 2103, 2291, 2360, 2363-2366, 2375, 2389, 2397
traitlets/utils.py                     0      0   100%   
traitlets/utils/encoding.py           23      7    70%   30, 53-58, 64-68
traitlets/utils/getargspec.py         64     52    19%   25-45, 49, 51, 55-86
traitlets/utils/importstring.py       16      0   100%   
traitlets/utils/py3compat.py         190    128    33%   20-21, 30-32, 36-40, 45-57, 64-79, 96-143, 151, 190-191, 199, 207, 211-291, 296-305
traitlets/utils/sentinel.py            8      1    88%   16
----------------------------------------------------------------
TOTAL                               2426    549    77%   
----------------------------------------------------------------------
Ran 289 tests in 0.307s

OK (SKIP=2)

```

### CODE REVIEW

**Comment by minrk** [comment]
Moving these wholesale doesn't really offer any benefit. While the genutils repo is 'deprecated' in that it won't get any new features, it's not going to disappear. While we should wean ourselves off of it, most of that should be done by switching to use of maintained packages, rather than copying all of the deprecated code into this repo.

Two particular changes stand out to me as things we shouldn't do:

- a Struct class, only apparently used in tests, is copied but has no real reason for use. These tests should be updated to not use Struct, rather than copying the class definition.
- py3compat shouldn't be copied over, instead most of it should be replaced by six. (See #117)

**Comment by lucasg** [comment]
Your answer raise valid points. Here's how I address it :

* for pycompat (& encodings), I agree that using six is ultimately the better move. Since it's already under way, you can ignore the commit.
* for the Struct class, unfortunately I've seen this type of class (re)written in various projects, but it never made its way onto the standard library. If you want to rely on a external package, I recommend the following classes :
	- attrDict : https://github.com/bcj/AttrDict
	- bunch : https://github.com/dsc/bunch
	- from argparse import Namespace (standard lib !)
* you rely on nosetest for unit testing, which is a quasi-deprecated project. You should upgrade to nose2 or py.test which are built upon unittest. Unittest has a decorator `@unittest.skipIf` for skipping test based on a conditionnal.

The rest of modifications are only basic utilities which, in my opinion, are better included in the library instead of requiring a package import (except from standard lib packages).

L.

**Comment by minrk** [comment]
That's exactly what I mean - rather than copying these things into traitlets, the better practices should be adopted, and the dependency on genutils slowly removed. *Some* things might want to be copied, but Struct isn't an example of one. It's only used for some minor convenience in the tests, and there's no need for it there, nor any use of it in actual code. We don't need an alternate bunch implementation either, we can just remove all uses of Struct. As you said, adopting an alternate test runner will let us remove the skip decorator. so we shouldn't copy the decorator to this repo.

**Comment by lucasg** [comment]
In that case, only cherry-pick the commits you find useful and/or otherwise close the pull request.

**Comment by SylvainCorlay** [comment]
@minrk I will rebase and update #117 sometime this week to get you something mergeable.

**Pull request closed without merging**
