### PR TITLE
ENH: Support default initialization from os.environ.

### PR DESCRIPTION
**Pull request by ssanderson**
@minrk this goes a bit further than what I suggested in https://github.com/ipython/traitlets/issues/99.

This adds `envvar` as a top-level argument to `TraitType`, and allows subclassses to define `default_from_envvar` to parse the environment variable string into an appropriate default value.

For scalar values, these are all straightforward invocations of `int`, `long`, `float`, etc.

For subclasses of `Container`, we try to parse the envvar value as JSON, with the assumption being that you shouldn't be passing anything too complicated to express as JSON as an environment variable.  I could see an argument for just barfing with a `NotImplementedError` in this case as well, which is what I did for `Union` because I wasn't sure how else to parse a reasonable default.

cc @femtotrader

### CODE REVIEW

**Comment by ssanderson** [comment]
Other design notes:

`envvar` is ignored right now if you specify a default callable via `@default` or the old `_name_default` syntax.  Should this be a warning and/or error instead?

**Comment by ellisonbg** [comment]
I have a slight preference for this to be on the Configurable subclass
rather than the top-level HasTraits.

On Wed, Dec 30, 2015 at 10:33 AM, Scott Sanderson <notifications@github.com>
wrote:

> @minrk <https://github.com/minrk> this goes a bit further than what I
> suggested in #99 <https://github.com/ipython/traitlets/issues/99>.
>
> This adds envvar as a top-level argument to TraitType, and allows
> subclassses to define default_from_envvar to parse the environment
> variable string into an appropriate default value.
>
> For scalar values, these are all straightforward invocations of int, long,
> float, etc.
>
> For subclasses of Container, we try to parse the envvar value as JSON,
> with the assumption being that you shouldn't be passing anything too
> complicated to express as JSON as an environment variable. I could see an
> argument for just barfing with a NotImplementedError in this case as
> well, which is what I did for Union because I wasn't sure how else to
> parse a reasonable default.
>
> cc @femtotrader <https://github.com/femtotrader>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ipython/traitlets/pull/157
> Commit Summary
>
>    - ENH: Support default initialization from os.environ.
>
> File Changes
>
>    - *M* traitlets/traitlets.py
>    <https://github.com/ipython/traitlets/pull/157/files#diff-0> (107)
>
> Patch Links:
>
>    - https://github.com/ipython/traitlets/pull/157.patch
>    - https://github.com/ipython/traitlets/pull/157.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/traitlets/pull/157>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ssanderson** [comment]
@ellisonbg this is actually on `TraitType`, not `HasTraits`.  The expected usage here would be:

```
class SomeTraitedClass(HasTraits):
    api_key = Unicode(envvar="MY_SECRET_KEY")
```

which should behave roughly equivalently to

```
class SomeTraitedClass(HasTraits):
    api_key = Unicode()
    
    @default('api_key')
    def get_api_key(self):
        return os.environ['MY_SECRET_KEY']
```

**Comment by ellisonbg** [comment]
Ahh, OK, thanks for the clarification.

On Wed, Dec 30, 2015 at 10:50 AM, Scott Sanderson <notifications@github.com>
wrote:

> @ellisonbg <https://github.com/ellisonbg> this is actually on TraitType,
> not HasTraits. The expected usage here would be:
>
> class SomeTraitedClass(HasTraits):
>     api_key = Unicode(envvar="MY_SECRET_KEY")
>
> which should behave roughly equivalently to
>
> class SomeTraitedClass(HasTraits):
>     api_key = Unicode()
>
>     @default('api_key')
>     def get_api_key(self):
>         return os.environ['MY_SECRET_KEY']
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/traitlets/pull/157#issuecomment-168054836>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
@ellisonbg I had the same thought initially, but when I looked at it for a bit this morning, it seemed like it would be simpler to implement in the base traits.

If someone sees a clean solution that would add it only to configurable traits, that would be fine, too.

**Comment by ssanderson** [comment]
> If someone sees a clean solution that would add it only to configurable traits, that would be fine, too.

Part of the issue here is that there are two different ways right now to specify default values for TraitTypes, and they're logically owned by different objects:

1. Registering a dynamic default method on a `HasTraits` subclass, in which case it's the **traited** object that owns the default behavior.

2. Passing `default_value` to an instance of `TraitType`, in which case it's the **trait itself** that logically owns the defaulting behavior.

The question, I think, is whether creating a default from an environment variable should be thought of as shorthand for creating a dynamic default method (in which case the logic for defining the default should be owned by `HasTraits` or `MetaHasTraits`), or whether it should be thought of as a slightly fancier way of specifying `default_value`, in which case the logic for defining the default should be owned by `TraitType`.

If we go with the "envvar default is owned by `TraitType`" model (which is what I've implemented here), then I don't think it makes sense to restrict this behavior to Configurables, since `TraitType` doesn't know anything about configuration.

If we decide that this functionality should be owned by `HasTraits`, then we could plausibly push it down to `Configurable` instead.

**Comment by rmorshea** [comment]
#158 is a step towards setting up env var defaults for configurable traits. Not sure if `eval` solves problems of coercion, but having the logic be a part of `TraitType` seems off to me.

**Comment by Carreau** [comment]
Closing as Stale for close to 5 years, Labelling accordingly, feel free to reopen or discuss.

**Comment by rmorshea** [comment]
Thanks @Carreau for help manage these issues ☺️

**Pull request closed without merging**
