### PR TITLE
Link tranform

### PR DESCRIPTION
**Pull request by francisco-dlp**
Add ``transform`` argument to ``link`` that takes a tuple with the forward and backward transform.

### CODE REVIEW

**Comment by minrk** [comment]
cc @SylvainCorlay for review

**Comment by SylvainCorlay** [comment]
Thanks.

To provide some background, one reason why we only added it to the directional case originally is that one needs to ensure that the two tranforms are inverses of each other to avoid infinite bouncing behavior.

**Comment by francisco-dlp** [comment]
Thanks for the feedback. Why would two transforms that are not inverses of each other cause bouncing behaviour?

I think that this is an useful feature. For example, say that I define a span selector and I want to fix its with without changing the class definition. With ``transform`` it is as simple as:

```python

import traitlets

class SpanSelector(traitlets.HasTraits):
    x1 = traitlets.Float()
    x2 = traitlets.Float()

ss = SpanSelector()
fix_width = traitlets.link((ss, "x1"), (ss, "x2"), (lambda x: x + 10, lambda x: x - 10))

```

Of course things may not work as expected if the transforms are not inverses, but I think that it is fair to assume that the users know what they're doing.

I have merged the current master into the branch to solve the merge conflicts.

**Comment by rmorshea** [comment]
@francisco-dlp the bouncing behavior would result from the fact that the two traits would always send each other different values from what they already have. Consider the following case of a 2D linked trait relationship:

```
a(b) = b**2
b(a) = a**2
```

Here, `a` and `b` are not related by inverse functions. Thus, if we were to set `a` with the value 2...

+ the change in `a` would cause `b` to update to 4
+ the change in `b` would cause `a` to update to 16
+ the change in `a` would cause `b` to update to 256
+ on and on forever...

The only reason that we don't get infinite recursion in 2D linked traits is when changes in a proverbial trait `b` do not cause a change in trait `a` - the lack of change in `a` is what kills the update notifications.

**Comment by maartenbreddels** [comment]
I think this is a useful feature, and it would be nice to have this in ipywidgets as well. Can we check in `_update_source` and `_update_target` if the transformations are actually the inverse? And raise an Exception is they differ.

**Comment by francisco-dlp** [comment]
I think that checking if the transformations are the inverse of each other is not trivial e.g. they may be the inverse of each other only in a certain domain.

**Comment by rmorshea** [comment]
@francisco-dlp because we check whether `link.updating` I don't think we have to worry about bouncing. However, it would be possible to break the consistency of the relationship:

```python
import math

class MyClass(HasTraits):
    i = Int()
    j = Int()
    
    @observe("j")
    def another_update(self, change):
        self.i = change.new * 2

mc = MyClass()

trans = (lambda x: x**2, lambda x: math.sqrt(x))
l = link((mc, "i"), (mc, "j"), trans)

mc.i = 2
```

```python
>>> mc.i
8
>>> mc.j
4
```

Inconsistent states will result when a consequence of a link's update changes either the source or the target trait. To resolve this issue we could raise if, after the update context is closed, the transform's relationship has been broken or not.

**Comment by SylvainCorlay** [comment]
> I think that checking if the transformations are the inverse of each other is not trivial e.g. they may be the inverse of each other only in a certain domain.

That is why we did not implement bidirectional transform originally!

**Comment by francisco-dlp** [comment]
@rmorshea, I think that the issue that you mention is unrelated to this pull request e.g.:

```python

class MyClass(HasTraits):
    i = Int()
    j = Int()
    
    @observe("j")
    def another_update(self, change):
        self.i = change.new * 2

mc = MyClass()
l = link((mc, "i"), (mc, "j"))

mc.i = 2
```

```python

>>> mc.i
4
>>> mc.j
2
```

@SylvainCorlay, there is of course a danger of things not working as expected if the arguments passed to a function are wrong or inconsistent, but this is true in general. Hence, I don't see why this should be an issue for adding an useful feature in this case.

**Comment by maartenbreddels** [comment]
If it doesn't cause bouncing around, and we just say it's the responsibly of the user/programmer to make sure the transformations are fine I don't see a reason not to implement it.

**Comment by rmorshea** [comment]
@francisco-dlp, true - inconsistency was possible before - however if we decided that we should raise when it's encountered, that would have implications for how we implement transforms.

**Comment by francisco-dlp** [comment]
@rmorshea, I have modified the code to raise a ``TraitError`` when the link doesn't work as intended. Thanks for pointing this out, as I think that it'll help prevent some hard to debug issues.

**Comment by francisco-dlp** [comment]
If anybody would like to use this feature while waiting for this PR to get merged (or not) you could try [link_traits](https://pypi.python.org/pypi/link-traits). The purpose of the package is to implement the dlink and link functions of traitlets for enthought traits. It can be used to link traits to traits, traits to traitlets and (redundantly) traitlets to traitlets.

**Pull request merged**
