### PR TITLE
Fix Change Dict Bug - Improper Old Values

### PR DESCRIPTION
**Pull request by rmorshea**
# The Problem

When it comes to default values, the `'old'` key in change dicts is often improperly assigned.

For example:

```python
class Foo(HasTraits):
    i = Int()
    @default('i')
    def _i_default(self):
        return 1
    @observe('i')
    def _i_changed(self, change):
        raise ValueError(str(change))

foo = Foo()
foo.i = 1
```

Surprisingly, the observer gets called here because `'old'` is `0`!

This is because `'old'` gets assigned via `i.default_value` rather than by a default generator.

# The Fix

Just call `getattr` to try and make a default value. If that fails `'old'` is `Undefined`.

side note: *the default must be generated **before** validating the new value. This is because any state changes induced by default generation should be overridden by setting/validating the new value.*

### CODE REVIEW

**Comment by minrk** [comment]
I'm pretty sure it was a deliberate, important change to *prevent* the default value generator from being called on first assignment, which caused problems in IPython when there are more complex default value generators. I think using `Undefined` or similar for the old value is better than generating a never-used value for `old`.

**Comment by rmorshea** [comment]
@minrk since defaults now only get generated at the time they are requested, `Undefined` makes sense. Either way though drawing `'old'` from `TraitType.default_value` doesn't seem right.

**Comment by minrk** [comment]
Most of the time, it is the right value. It's only when a dynamic default is defined that it gets skipped.

**Comment by minrk** [comment]
Using Undefined when there's a dynamic default makes sense, though.

**Comment by rmorshea** [comment]
Because of #349, I'm not so sure that it's valuable to distinguish between a default declared here `TraitType(default_value=<value>)` and one defined via `@default` anymore - now, a trait's default is **always** decided at the time it is first requested, and never during `instance_init` as was previously the case for "static" defaults.

Using `TraitType.default_value` means that it's possible for `'old'` to be inconsistent with expectations whenever `@default` is used. It seems that it would be better to give no information about the old value, than to give information that's false.

**Comment by rmorshea** [comment]
@minrk looking through old issues I found this [bug](https://github.com/ipython/traitlets/issues/287#issuecomment-255456913) wherin using `TraitType.default_value` can result in a failure to validate new values in `hold_trait_notifications`.

**Comment by minrk** [comment]
That makes sense.

**Comment by rmorshea** [comment]
@minrk, `old=Undefined` breaks multiple tests...

Is it possible that the new on-request default generation, might bypass the problems you alluded to?

*the old way being default state initialization during `HasTraits.__init__`*

**Pull request closed without merging**
