### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by rmorshea** [comment]
@martinRenou is this related? https://github.com/ipython/traitlets/issues/497

**Comment by martinRenou** [comment]
I'm not quite sure it's related to `Sentinel` not being exported. I'm trying to fix the
```
/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest_warnings/__init__.py:44: UserWarning: pytest-warnings plugin was introduced in core pytest on 3.1, please uninstall pytest-warnings
  warnings.warn('pytest-warnings plugin was introduced in core pytest on 3.1, please '
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 3.3.0 (/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.6'))
```
That you can see on those builds: https://travis-ci.org/ipython/traitlets/jobs/513025651

**Comment by rmorshea** [comment]
Hmm, this looks like `pytest` 3.3 has already been installed inside the virtualenv, but something is requiring >=3.6

**Comment by martinRenou** [comment]
Yeah, there is also this warning: `pytest-warnings plugin was introduced in core pytest on 3.1, please uninstall pytest-warnings`

**Comment by rmorshea** [comment]
I wonder whether this would be fixed if you set `pytest==3.3` [here](https://github.com/ipython/traitlets/blob/master/setup.py#L88) since it seems like its during the installation of extras for traitlets that we're encountering this error.

**Comment by minrk** [comment]
This now gets the tests passing, except for what are actual failing traittypes tests due to a breaking change in traitlets, in our handling of Undefined. This is open on traittypes as https://github.com/jupyter-widgets/traittypes/issues/33 since it seems like what they are doing doesn't make a lot of sense, and I'm a little surprised it works in stable traitlets.

**Comment by minrk** [comment]
Thanks for the PR!

**Comment by martinRenou** [comment]
Sure! I also noticed the tests are using deprecated stuff:
`DeprecationWarning: on_trait_change is deprecated in traitlets 4.1: use observe instead`

**Comment by minrk** [comment]
Yeah, the tests verify that deprecated APIs still work, we shouldn't stop testing them. We could suppress the warnings, though.

**Pull request merged**
