### PR TITLE
Remove uses of ipython_genutils.py3compat in favor of six

### PR DESCRIPTION
**Pull request by Carreau**
Just rebased @SylvainCorlay's work (#117)

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks. There were a few occurrences of `string_type` that were added since I opened the original PR and should be replaced with ` `six.string_types`

**Comment by Carreau** [comment]
Yeah, I saw that with failing test. Fix in progress. Tests passing locally now.

**Comment by Carreau** [comment]
Travis is happy.

**Comment by minrk** [comment]
incremental improvements, woo!

**Pull request merged**
