### PR TITLE
reintroduce deprecated support for old-style container args

### PR DESCRIPTION
**Pull request by minrk**
alternative to #338, we should only pick one.

The old, undocumented (I think?) way of specifying containers on the command-line continues to work with a deprecation message.

The way I've implemented deprecations here prevents new-style args that pass the 'looks like a literal' test. That means there would be no way to properly specify the list `["[1]"]` on the command-line. I'm not too concerned about it, but it's a theoretical issue. The alternative to _that_ is to keep the logic here for warnings, but _don't_ try to support the old-style args. That way you can specify anything in the new-style, and users will get a pointer if they use the old-style, but attempts to use the old-style will generally result in errors.

I have a slight inclination toward deprecate-and-keep-working over break-with-informative-message, but if someone can point to a more serious problem that the deprecation will break, I'm happy to change.

closes #338

### CODE REVIEW

**Comment by ankostis** [comment]
But if the old behavior was undocumented, and problematic, why should we keep it around?
Probably would cause more problems in the future if people start really (ab)using it.

**Comment by minrk** [comment]
@ankostis while rare, people used it. Deprecations, where feasible, are always nicer than breaking things.

**Comment by Carreau** [comment]
+1

**Comment by minrk** [comment]
Thanks, @Carreau!

**Pull request merged**
