### PR TITLE
Fix backward compatibility and tests

### PR DESCRIPTION
**Pull request by Jamim**
Hello,

I'd like to propose some fixes.
Hope you find them useful.

Thanks!

### CODE REVIEW

**Comment by Jamim** [comment]
Hi @minrk,
Could you please take a look at this PR?
Thanks!

**Comment by Jamim** [comment]
Hello @rmorshea,
Can you please take a look at this PR?
Thank you!

**Comment by rmorshea** [comment]
@Jamim I've been swamped recently. I may be able to take a look at this in the next few days.

**Comment by rmorshea** [comment]
Didn't realize the changes were so small, and it's great that this restores the tests. Thanks!

**Comment by Carreau** [comment]
> "is deprecated in traitlets 4.4, and may cause "

I'm not sure there was or ever will be a 4.4 so may need to get updated.

**Pull request merged**
