### PR TITLE
simplify deprecation of MetaHasTraits

### PR DESCRIPTION
**Pull request by minrk**
rather than using a generic mixin deprecated class factory that's only used once

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by SylvainCorlay** [comment]
@minrk actually it could make sense to make `MetaHasDescriptors` inherit from the deprecated `MetaHasTraits` rather than the opposite.
In `nbconvert/exporters/exporter.py`, we have a `isinstance(preprocessor, MetaHasTraits)`, which will not work in the current state of things.

**Comment by minrk** [comment]
@SylvainCorlay good point, done. I also opened jupyter/nbconvert#134, which removes the check for MetaHasTraits, which was probably never the right thing to do, anyway.

**Comment by SylvainCorlay** [comment]
Merging (!!)

**Pull request merged**
