### PR TITLE
Fix copy(HasTraits) by copying `_trait_values` dict

### PR DESCRIPTION
**Pull request by ankostis**
- Added also TC.
- Waiting for response on question whether must reset `_cross_validation_lock' lock back to `False` 
  (asked also in #481).

### CODE REVIEW

**Comment by ankostis** [comment]
All test-cases pass, except from Appveyor on Windows (expecting #483 to merge for that).

**Comment by minrk** [comment]
Makes sense. I'm not sure what to do when cross_validation_lock is held. It does make sense to clear it, but what's the state going to be if a HasTraits is copied in the middle of pending changes? Should the cross-validation be forced to finish as part of the copy?

**Comment by ankostis** [comment]
Ok, pinned the `_cross_validation_lock=False` when cloning.

> Should the cross-validation be forced to finish as part of the copy?

Maybe raise an exception, to fail early?

**Comment by ankostis** [comment]
Btw, I have pushed a relevant commit about `utils.sentinel.Sentinel` ignoring copy/deepcopy.
Sentinels must not change, or cloned traits fail defaults 
(a a really nasty bug discovered a year ago, please don't ask me more).

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
