### PR TITLE
enable property-like api for event handlers

### PR DESCRIPTION
**Pull request by rmorshea**
a mockup for property-like event handler decorators

```python
class A(HasTraits):
    i = Int()

    # kwargs can be passed
    @i.observer(type='change')
    def i(self, change):
        print('i changed')

    # the generalized api
    @i.decorate(ValidateHandler)
    def i(self, commit):
        return commit['value']*2

    # streamlined api
    @i.default
    def i(self):
        return 1
    
class B(A):
    
    @A.i.default
    def i(self):
        return 2
```

The reason this isn't particularly clean to implement under the hood is because the decorator is run prior to when the trait has received its `name` attribute.

### CODE REVIEW

**Comment by minrk** [comment]
@SylvainCorlay @ellisonbg do we want to hold 4.1 for this API change? It doesn't seem like the 4.1 API is settled, yet.

**Comment by SylvainCorlay** [comment]
@rmorshea @minrk I am not really sure of what this would bring compared to the current API, which very naturally extends to observing / validating multiple trait attributes with `@observe('foo', 'bar')`.

**Comment by ellisonbg** [comment]
I don't think this should go into 4.1.This represents a massive shift in think about the API compared to where things have been going for the last few months. @SylvainCorlay thoughts?

**Comment by rmorshea** [comment]
@SylvainCorlay, @Carreau suggested it, so I made a mockup of the idea. Also, I just pushed a commit.

**Comment by rmorshea** [comment]
@ellisonbg I'll be on campus shortly.

**Comment by minrk** [comment]
It does seem like a big shift, that's why I asked. It doesn't seem like a good thing to ship a new API in 4.1 and immediately deprecate it in favor of a totally different one in 4.2. And I don't think we should have two parallel active APIs, so to me shipping 4.1 without this suggests committing to not having the property-style API, at least for a while. I do like the idea of traits looking more like properties, which seems more grokkable to those already familiar with Python.

Perhaps I'm overestimating the cost of having two ways to do everything, though.

**Comment by ellisonbg** [comment]
Yep, I completely agree that we should only have 1 main API. It seems like
we have worked really hard for a number of months to create the new API and
that this PR goes in a completely new direction. I am +1 on not putting
this into 4.1 and probably not putting it into future releases without
first seeing how the existing API goes over.

On Tue, Nov 24, 2015 at 1:10 PM, Min RK <notifications@github.com> wrote:

> It does seem like a big shift, that's why I asked. It doesn't seem like a
> good thing to ship a new API in 4.1 and immediately deprecate it in favor
> of a totally different one in 4.2. And I don't think we should have two
> parallel active APIs, so to me shipping 4.1 without this suggests
> committing to not having the property-style API, at least for a while. I do
> like the idea of traits looking more like properties, which seems more
> grokkable to those already familiar with Python.
>
> Perhaps I'm overestimating the cost of having two ways to do everything,
> though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/traitlets/pull/134#issuecomment-159406127>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by SylvainCorlay** [comment]
The separation of `BaseDescriptor` and `HasDescriptors` should allow anyone to experiment with descriptors having a different logic than the core traitlets if really needed.

**Pull request closed without merging**
