### PR TITLE
add attr-access to change dicts

### LINKED ISSUE #217: observe's handler change should likely be an object.
It always have the same field, and is annoying to access through keys.
Maybe a NameTuple for immutability ? not sure if you can access a named tuple with square brackets.

### PR DESCRIPTION
**Pull request by minrk**
it's still a dict, so everything should be 100% backward-compatible.

include yet-another implementation of bunch in utils.bunch

closes #217

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
:+1: this is almost as cool as JavaScript :stuck_out_tongue:

**Comment by SylvainCorlay** [comment]
It would be nice to do the same thing with the `proposal` dictionary for cross validation.

**Comment by SylvainCorlay** [comment]
@minrk lgtm except for the comment above.

**Comment by minrk** [comment]
@SylvainCorlay good call, done. Are there any other dict-events at this point?

**Comment by SylvainCorlay** [comment]
I don't think so.

**Comment by SylvainCorlay** [comment]
Awesome, this is a significant improvement IMO.

**Comment by jasongrout** [comment]
Nice! Thanks!

**Comment by Carreau** [comment]
Thanks ! That's much more readable, and I'm sure completers will allow to complete that easily.

**Comment by jasongrout** [comment]
In order for completers to work, we should add a `__dir__` to the Bunch: https://docs.python.org/2/library/functions.html#dir

**Comment by minrk** [comment]
@jasongrout added keys to dir in #238. It doesn't mess up completions of dict methods since the keys are just added.

**Pull request merged**
