### PR TITLE
Add NDArray trait type

### PR DESCRIPTION
**Pull request by maedoc**
This adds an NDArray trait type that validates on shape and dtype constraints.

### CODE REVIEW

**Comment by rossant** [comment]
@maedoc just wondering what's the status of this? 
Is it conceivable to have a ndarray trait notify content changes like:

```python
class A(HasTraits):
    arr = NDArray(...)

a = A()
a.arr = np.array(...)  # ==> notify
a.arr[0] = 1  # ==> notify
a.arr += 1  # ==> notify
...
```

**Comment by Carreau** [comment]
We will restart Traitlets from scratch after 3.0, (spliting it again from IPython)

Once this is done, the more the merrier.

**Comment by rossant** [comment]
OK. Any idea of the timeframe? What's wrong with the current implementation?

**Comment by Carreau** [comment]
> OK. Any idea of the timeframe?

A few month. 

> What's wrong with the current implementation?

Nothing, this just copy and past of old IPython version, which has evolved too much with widgets. 
I basically spent a week creating this package with a wrongly set mutex. So the backend reply to me that transaction could not be applied, and I need to reperfom it. 

I just need to find a week to say : """Don't F%^& dare touching `Traitlets` code for a week"""
and re-do the work, then release mutex. It's doable in 2 days if I don't move the documentation now, and I don't try to move the `Config` part at the same time. Probably a day with cafein, but think one more day to review.

**Comment by maedoc** [comment]
@rossant I seem to have lost this repo, but `a.arr = r_[]` could notify while `a.arr += 1` would require an ndarray subclass, as any reference to `a.arr` results in the ndarray and not the trait's data descriptor `arr` (whic is the thing wrapping access to the ndarray).

**Comment by maedoc** [comment]
@minrk why no action?

**Comment by Carreau** [comment]
I think that because most of that is in [numtraits package](https://github.com/astrofrog/numtraits) in [`@astrofrog/numtraits`](https://github.com/astrofrog/numtraits).

**Comment by ellisonbg** [comment]
I thought we were going to put these types of things here:

https://github.com/jupyter-incubator/traittypes

**Pull request closed without merging**
