### PR TITLE
warn on misstyped config options

### PR DESCRIPTION
**Pull request by Carreau**
That have annoyed me for too long: 

```
$ ipython notebook --NotebookApp.ignoreMinifiedJs=True
[W 10:15:45.741 NotebookApp] Config option `ignoreMinifiedJs` not recognized by `NotebookApp`, do you mean : `ignore_minified_js`
[W 10:15:45.742 NotebookApp] Unrecognized JSON config file version, assuming version 1
[W 10:15:45.743 NotebookApp] Config option `ignoreMinifiedJs` not recognized by `NotebookApp`, do you mean : `ignore_minified_js`
[W 10:15:45.744 NotebookApp] Config option `ignoreMinifiedJs` not recognized by `NotebookApp`, do you mean : `ignore_minified_js`
[I 10:15:45.787 NotebookApp] The port 8888 is already in use, trying another random port.
[I 10:15:45.793 NotebookApp] Serving notebooks from local directory: /Users/bussonniermatthias/dev/notebook
[I 10:15:45.793 NotebookApp] 0 active kernels
```

```
$ ipython --InteractiveShell.color=linux
[TerminalIPythonApp] WARNING | Config option `color` not recognized by `TerminalInteractiveShell`, do you mean one of : `colors ,color_info`
Python 3.5.0 |Continuum Analytics, Inc.| (default, Oct 20 2015, 14:39:26)
Type "copyright", "credits" or "license" for more information.

IPython 4.1.0-dev -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
```

It does warn only if if find an option which is **close** by standard definition of **close** from difflib.

This **does** make  `SingletonConfigurable` a `LoggingConfigurable`.

I'd like @fperez input on this one, as there might be historical reasons not to do it.

### CODE REVIEW

**Comment by minrk** [comment]
There's not a reason, I've been thinking of doing something like this for ages. +100. +1 to making SingletonConfigurable Logging, too.

**Comment by Carreau** [comment]
Yeah, my only reason **not** to do that, is that I **hate** difflib.

**Comment by minrk** [comment]
Add a test?

**Comment by Carreau** [comment]
Likely a good idea. 

Have to figure out how.

**Comment by Carreau** [comment]
> Add a test?

done.

**Comment by Carreau** [comment]
Well, for Application at least.

**Comment by Carreau** [comment]
Also we could try to do the same in `_find_my_config()`, but I expect there will be more false positive.

**Comment by Carreau** [comment]
Hum there is a bug (maybe in IPython, not here) if you use the config magic. It keeps the old set config:
```
In [4]: %config InteractiveShell.color='gray'
[TerminalIPythonApp] WARNING | Config option `color` not recognized by `TerminalInteractiveShell`, do you mean one of : `colors ,color_info`

In [5]: %config InteractiveShell.colors='gray'
ERROR: The 'colors' trait of a TerminalInteractiveShell instance must be any of ('NoColor', 'LightBG', 'Linux'), but a value of 'gray' <class 'str'> was specified.

In [6]: %config InteractiveShell.colors='NoColor'
[TerminalIPythonApp] WARNING | Config option `color` not recognized by `TerminalInteractiveShell`, do you mean one of : `colors ,color_info`

In [7]: %config InteractiveShell.colors='NoColor'
[TerminalIPythonApp] WARNING | Config option `color` not recognized by `TerminalInteractiveShell`, do you mean one of : `colors ,color_info`

In [8]: %config InteractiveShell.colrs='NoColor'
[TerminalIPythonApp] WARNING | Config option `colrs` not recognized by `TerminalInteractiveShell`, do you mean : `colors`
[TerminalIPythonApp] WARNING | Config option `color` not recognized by `TerminalInteractiveShell`, do you mean one of : `colors ,color_info`

In [9]: %config InteractiveShell.colors='NoColor'
[TerminalIPythonApp] WARNING | Config option `colrs` not recognized by `TerminalInteractiveShell`, do you mean : `colors`
[TerminalIPythonApp] WARNING | Config option `color` not recognized by `TerminalInteractiveShell`, do you mean one of : `colors ,color_info`
```

**Pull request merged**
