### PR TITLE
Fix autodoc

### PR DESCRIPTION
**Pull request by talboito**
4fdc908 changed HasTrait.add_trait -> HasTrait.add_traits.

The docs and the specific autodoc reference for that method don't appear to have been updated alongside the code.

### CODE REVIEW

**Comment by Carreau** [comment]
Great ! Nice catch.

**Comment by Carreau** [comment]
(just try to avoid merging other PR in your feature branches if you can, but it was small enough this time).

**Comment by talboito** [comment]
Oh. Sorry. Will do.
		
        
		
		 ---- On Wed, 10 Jun 2015 08:21:32 -0700  notifications@github.com  wrote ----(just try to avoid merging other PR in your feature branches if you can, but it was small enough this time).

**Comment by Carreau** [comment]
> Oh. Sorry. Will do.

No problem. Each project have its own policie it can be heard to follow.

**Pull request merged**
