### PR TITLE
Use NoDefaultSpecified as sentinel for Type default

### PR DESCRIPTION
**Pull request by takluyver**
Instead of None

Prerequisite for fixing jupyter/nbconvert#41

### CODE REVIEW

**Comment by takluyver** [comment]
WIP

**Comment by takluyver** [comment]
OK, this is ready for review now. The logic around default values for `Type()` traitlets is a bit hairy, but I think what's there now should work.

klass | default_value | desired k | desired dv
-------|------------------|--------------|-------------
None | NDS | object | object
None | None | object | None
None | value | value | value
value | NDS | value | value
value | None | value | None
value | value2 | value | value2

**Comment by takluyver** [comment]
This is necessary because if we use `None` as the value meaning 'nothing was specified', there's no way to explicitly ask for a default of None, which is what we really want to do in nbconvert.

**Comment by jdfreder** [comment]
Yay two null types, like Javascript : ) .  Have you thought about naming this as `Undefined` instead of `NoDefaultSpecified`?  That really is what `undefined` is for...

**Comment by takluyver** [comment]
There's Undefined in there as well. I'd like to collapse Undefined and NoDefaultSpecified down to one object, but that's another PR. For the moment, Undefined is what's used as an attribute, and NoDefaultSpecified is used in constructor parameters.

**Comment by SylvainCorlay** [comment]
+1 to make it a different PR for collapsing. I recall that I looked into that and there was a lot more to change.

**Comment by minrk** [comment]
Makes sense. Want to add some tests to exercise the different cases? I could imagine getting a little mixed up and not noticing that we broke something here for a while.

**Comment by minrk** [comment]
Also :+1: for collapsing Undefined and NoDefaultSpecified.

**Comment by takluyver** [comment]
Added tests

**Comment by minrk** [comment]
huzzah!

**Pull request merged**
