### PR TITLE
Making a bound method in the @observe decorator

### PR DESCRIPTION
**Pull request by SylvainCorlay**
The solution proposed by @sccolbert to the problem with unbound method in the observe decorator. @rmorshea.

### CODE REVIEW

**Comment by sccolbert** [comment]
Looks good to me, based on the previous discussion.

One more thing to think about: do we really want to be holding on to bound methods as listeners? This means the lifetime of the bound instance is tied to the lifetime of the object which is being observed. In Atom, I decompose a bound method into its constituent function and instance, and only keep a weakref to the instance. When invoking that connections, I first deref the weakref. If the instance is still alive, the method is invoked, otherwise the connection is removed. 

This pattern allows a listener to be garbage collection independently of the thing emitting the change.

References (C++ but the idea is the same):
https://github.com/nucleic/atom/blob/master/atom/src/methodwrapper.cpp#L90
https://github.com/nucleic/atom/blob/master/atom/src/methodwrapper.cpp#L47
https://github.com/nucleic/atom/blob/master/atom/src/observerpool.cpp#L220
https://github.com/nucleic/atom/blob/master/atom/src/observerpool.cpp#L227

**Comment by tacaswell** [comment]
mpl has a call back registry which does the same decomposition  (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook.py#L454 and the class right above it).

**Comment by SylvainCorlay** [comment]
We allow using any function as listener when using the `observe` method instead of the decorator.

**Comment by rmorshea** [comment]
SylvainCorlay/traitlets#1 replaces the api for cross validation which currently uses `_name_validate`.

**Comment by sccolbert** [comment]
> We allow using any function as listener when using the observe method instead of the decorator.

We do the same thing in Atom. The `observe` function checks if the listener is a plain function. If it is, it's just added to the listener list. Otherwise, a method is broken apart and wrapped in an object as described above. The object is callable, so the dispatching code can treat it the same as function. 

Additionally, it reimplements `__eq__` to return  `False` when the weakref'd instance is collected so the manager knows the wrapper can be removed. It looks very similar to the class @tacaswell posted. Atom's is contained in the `methodwrapper.cpp` listed above.

**Comment by SylvainCorlay** [comment]
It should be a simple addition though.

**Comment by sccolbert** [comment]
Sure - I just brought it up while we had attention to the topic.

**Comment by SylvainCorlay** [comment]
Anyone with commit rights wants to hit the green button?

**Pull request merged**
